creates a module that translates between english and pig latin
badmckinney/pig-latin-translator pull request #1
Opened 2019-01-15 21:18 UTC by badmckinney

2019-01-16 02:32 UTC, taesup requested changes

2019-01-16 02:32 UTC, taesup commented on pig-latin.js
> +      return words;
this line will never be executed because both the if and the else have a return.

2019-01-16 02:32 UTC, taesup commented on pig-latin.js
> +            let pre = word.slice(i);
The variable names here are actually the opposite of what they claim to be. (pre, post)

2019-01-16 02:32 UTC, taesup commented on pig-latin.js
> +    console.log(translated.join(" "));
Remove console.log

2019-01-16 02:32 UTC, taesup commented on pig-latin.js
> +    debugger;
Remove debugger statement.

2019-01-16 02:32 UTC, taesup commented on test/pig-latin-spec.js
> +console.log(translator().translateEng);
Remove console.log

2019-01-16 02:32 UTC, taesup commented on pig-latin.js
> +    console.log(translated.join(" "));
Remove console.log

2019-01-16 23:53 UTC, badmckinney commented on pig-latin.js
> +            let pre = word.slice(i);
I named the variables based on what they would be in the translated word, should I reverse it?

2019-01-17 00:06 UTC, taesup commented on pig-latin.js
> +            let pre = word.slice(i);
I think it's best to name it in the context of the function. That way as you're reading through the code it makes more sense, especially if this was a larger function or a function is a larger code base.

2019-01-17 02:26 UTC, merged